[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "198bda652c9d9c6be76c3da0c29d89a195ee5d70"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "fce69dff2d2bb6548eabbd78ac063e8b3f48175fb9920bad5565c988956dc79f"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "1dcf19aab85ed22205a7d6dcb34b5f7932ccafa9"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "3be7bd1d60d8a8c1e525692cc0e5e770e8cc09f90e73dae3da1098d62f11995a"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "bf20a5e8a50bfcc35c0d02954b6d622d9ea5e1be"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "beeaceb6d06f73473a74e8e935b4e3f6473941c2062461bb9f512ba23236ec4b"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "66b83ad6dc970407ae7296e280f4283deb015a26"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "63be8ed42ddd4543f387a4c41c2f7cf6a497bb76bc3602fe071c6036c198b329"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "14ec7a3cd74039d07588f581de07a94fdcc607ec"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "4c4295e1ec1c96643a6798c39893263a4235cd95f0fb6ef5666b39958fc96bb4"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "ac63b9b3a31789882dde6cb119887a7635fc6211"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "1dfcee90ababaa45f392ab3d01e1bb95a70b09932c7bf61b65ceaa883946d74d"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "ca0674033c1b529224860b3a0a14319c3e6d0e5d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "d7939f58ab5d8cd8ed61ccd478ef03dbe5ca680636c5f04269957fca163147fa"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "ee02db18921f42e3cf2fba8ab5b93dbd75a1b76a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "734ae10ac76bec701f641313d50925b0ec800b4a89e08908ab8ff6abed5d19c5"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b11cde0bb8e3fd598b42266fdf1c18460834cb8d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "380d01673a0b8263d0f90f1ebe23d7686716b881cccd51df6fe25491c2be3460"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ad8e124005858350e9c46b2ef5eb57124b34cb36"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "c2cc117d6f335f7c697992dc5d5d4e725d2d43cabff9925381d76363e7c22bc3"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "12db9fd3b8e44684a6358c0e87ef935f4e5eec5d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "053416224370ca668dedbf90fff6e89e8451e195643cb93a29756423b26c7873"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "60005105bc85e38202f808d3718ee6b024973eb8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "5f52f6a5f1764cdc138735f17ea6552c0ac9013829a4687d9f34396ef9a459f8"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
