[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "a948b2ceb647a857100dafe3c129e2e75925f9cb"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "23ad750eb90986f7cede69d71617fe797dcdf9393fc7beb3f1150c4b24ea4ed1"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "35866a19074d4f5975285dbc2969d8bd645efabb"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "3a90e7dff3c40bef5701e716cd5879c9b24f773d1d03b26ff21b1d6a583e9237"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "948037eff0f66c7bf97e87eb9dceef8eccf97406"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "cb6c6b2fc157e1ab659f5f93e376e480285b2879037f99a67e78ed0427b4af0a"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "e84993c650352372fe289b6bc245ad5b65ca2b9c"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "a665f474de64d314c2c116976eb461c7b0bcd003324688eaa108b9adb787e5ab"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "539b60c30d0e481bb263635cb47c7a66562bb544"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "69b4442bee368333fb4385e12961e44809c84dcbd51162d180357412c248ae1d"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "aecfaa98f43864d3b61effbe9b2ab9ad727b9804"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "e5ca205d82a4315b2e55a601ee0dd5b21afd733f2a3952fd4fb172b1094389c7"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "45f367fbe39711c9e8944acbae64de94ad557c57"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "ffa8c5f2fb127b00599dbd596bdd15c4bb9b7c4f3ee1da32054cc89b7b20a15d"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "a3e7090eaf6f77bde8f9ba443a15890551839474"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "74e67976c539fcb3a58d984ce8731c12d217975939a0a7b5eb094d9f20a5f42d"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bb6a73fde35384c4006bce4f9f876f50c8a87781"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "d451266b2e395115eb8299113ccb2236f1a6dea6f1fd9af1bd9c713537240322"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "5baf496158e8165285e1ee1a39847182a7a124f8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "b42978735894e45d3aef8e7aca490092dde680b6946ec109dbd21c4276fcc218"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "7935b7d2fe9f7924e5feef52b1ec7da5f350f2df"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "a569800b0829f285f719035ebf55afeea93b59fa56107b5b1d8faef2b0841b50"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "fdac4da56903a2ce521c5722696f80ad0350be28"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "f3119dd9362c1f4405707bf6f443e79f07fb37b83988026efa8644a34c071b58"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-envvar_test/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
