[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "0515058185bf4e755ea2b988f73b797d29ae033b"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "2550890ea2fbaa413e47cb4b8c81fee43a4c2e6c1ddc48f74c801b307d31d8c0"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "a754b131c1627d826b91d79ef9521665ccbe2b0f"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "73f6a0536ce55000586c96bb397496502ca783348db644e3dbac47dddac227d6"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "e4bad1bb4f316df051e24d6d7b5b57f69c2b1b5b"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "661076b2c767f1eb48f7151ef12208fd8b76194432914aa88c43fae45eb256b6"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "46b57a8a5ad7c9d61792c3834b61e410ee28ea2c"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "d56315d9148521d92a26f60244ddfa85c4a52ed4861432b3a9a904a51f0a55b8"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "c0e8e0fbac176d8c8ed6fe0270cf9989b7b2f15d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "524d0e847982c3aa0f182f73825e49f4d8b6ea39ef78ea6a7f5552c6f81afe56"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "84f5714807fa01889aa3ab45beba91eafd7f1f3f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "c0e1a462198bfb9716df287a4c6b213d2b63ad8b9a2d1a6e743b63dd9c3fdced"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "cfbeb01b737b41c9bc7c2db159ea3ba2905ecf11"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "a2ef5b7c6b6ce4a372ebede720f87ddb7a1a02eeaca240f670c18bfac8353109"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "944ed22511c0ba4a16f89338f0c0f89002b00d74"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "448bc1563fe7b7e15c5769d2aa200e24ba50cad0f7689437c4559c081ccf55eb"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2bbd7f93c6b18a1c63c3720e06e08ba6116905bd"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "60de02d060c88874df65ab8342f5028e98a84554185a39ead20bbc656bb8609e"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e417f680bf1b5dad919a745ce59548efce5cd40a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "b55f2462cfd5b0f252605f21d449a3b5dbfaf2f51cd3a277b001676f67253469"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "cbb5d859a53ec281048b4fe5e1cbbe3e1a99bc3e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "08d3652a13b0265fc40fd022bd1af8e70f92d5a48e6fd0dd0c66f18481202b81"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e529a90247f6574ed7021024793bbab2557908ea"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "690b769706cdc7f18203dcc2a3f5cddbacdc8ece2afcc866493be47d9d24efca"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
