[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "73f80dc1e23b79b94900cf52f63e85128c819688"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools.download]]
    sha256 = "a29ada15b8a53aed1d04bc7288ae8d68272a6029b52a3ea29d29dbf8cdb9fcf5"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "d199b149df4713b77cc7bbb6a5e0547507cd0df3"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools.download]]
    sha256 = "edf5c3b0b823c577ea80084ebb13950b1f2e71e018ca59a1b0334e30990f017a"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "c5f936cb78356288b7cad24930cd3dbdcff094ab"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools-build_log.download]]
    sha256 = "fa5ad374395b81ed5ebbc47bacf30c9e1379bf982fc346b80902502f3f38f06d"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "c97205fc426cb65ac2fcd780cfe4e873d90dc5e6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools-build_log.download]]
    sha256 = "d195003f33f89a1d4c1c0b23d4c1007ceed948866754f106d9ce1483455088e4"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2c2c13367a5e09a915bbf473190433cba3919e39"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools-extract_log.download]]
    sha256 = "99f748addf39f02ab8c5f1e4077d8078ea8c1435ad9f9065e9fc6f43e74db4ee"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c33e701ccfff3e16de2998d766ed4c272a5f8412"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[CCTools-extract_log.download]]
    sha256 = "2a37094be750ad4d130e04510e44db13040a1a0e185d05c9f58ae9f4171a4787"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1-GCCBootstrap-x86_64-linux-gnu/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"
