[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "97bc3aa48fa848be00d40ec26a9a3220240be63e"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "aa513998a9fac7367b98146b4cea478a716588c363c9d4e8b637776c3f97af3c"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "07b6c98d91807723e561f66368e731ded9ea5b86"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "a2292dcddb3b60a03d06a8954e15953eed130d13bac07e1d7fc5a64a7f41ec41"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "0de3482f1cd18bc3e26f462653f5e22860cfef20"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "e376997caac7639854058da1685846e8388a15eda1b1f3cf009664ac544b5a3b"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools]]
arch = "aarch64"
git-tree-sha1 = "4670f81999734f3b957a3991b0ab16c8d3a1c8b1"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "c50bfff24d2859834cd431b47db4b159a5822c0aa33b8f876044127b67a2e2ea"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "c49d830328db84ac61a0c27987e36b7387c89246"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "4a5eefd03d942a2bdd0a9ed566e639b10fc3b4281c840d829e814eac31c0ebb8"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "006400d15fb67161addd81936112fd8183e370df"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "51da9d66ed6d75544a26ee7334138b20b300459189635fba3bb0af9338882282"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "c6767e0fa9a2b2bdfd4f6865773d2fa7ea5212c8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "9c7ebdaf693c721b46618cf1624744df7ba2434a4a3bbc9406530e423663ad85"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-build_log]]
arch = "aarch64"
git-tree-sha1 = "146f1a70c88ce7caf242b991abe9de20afc0fb41"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "ab51ca3eeae3f86a802d6c5213d62470d3f8830c82cfb42de8b37f1664498013"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "4cc36e035f76e687c9b9b219f4a7583d6974884c"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "2b63b991b8f509be60243f309287b092c9854db8ad359e43bb33547b316e5fca"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "095758cc0e99fdd246a86f3c14a549b87845ab26"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "965747617ed9adc9ce63728c75450617edcb3d89e1af4197e11ff442a9ac4ebc"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "afd6fce6d06bf161039c581bd7db6b5a8be0503d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "878329b9c85bc735679b8a84422f05e3d7f94bf9cfb4d40cd3a615d5409d318e"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[CCTools-extract_log]]
arch = "aarch64"
git-tree-sha1 = "41aea63dd1a989731ebc85d49180e1fd11f6afa5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "86b5214bfdde638d3fc609cf349f34eb68bb7d46487d81a3a1ff5b6953056add"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-aarch64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
