[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "961b6a368be3ee7a01290b3824bd698708c1aa4b"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "ee2581ed37a08437ac9ffd92f5200e2d4581276a54fd8fed2de12740c0edd981"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools]]
arch = "x86_64"
git-tree-sha1 = "816515f2fed6ef8d2243c0c4c2d361b3e965b0de"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools.download]]
    sha256 = "e8979df193ede615e2770d0bbd275d1feddf014cf0eea58e30dde4c148d41b22"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "86a65d96f9896e984d4d759867fcca1539866669"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "b4bcb9fb564e2f9b24676a58bc51ebbf11b61ee107872e8fb68196b9a9e5abeb"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-build_log]]
arch = "x86_64"
git-tree-sha1 = "3f9ca239fcf997733e72dfe659d0258a5318ceb8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-build_log.download]]
    sha256 = "88df965dfb1c50f921f85d5f0788dd9c9dffe7d2f6169b92a88cae3c95b8ca05"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-build_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"

[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a4fd5e02c6ed657c3fa001837eab7f0873d8034f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "6455400869550069025b590fae32519a76d6a11ec0244db408f669fa342eda85"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[CCTools-extract_log]]
arch = "x86_64"
git-tree-sha1 = "91115eb86d92541287bfba05b9c5d796c3bd4342"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[CCTools-extract_log.download]]
    sha256 = "114baf26b1ae51029c360e7efa08663493e8252f8f91385bafce86f0a0a0c2aa"
    url = "https://github.com/staticfloat/CCTools_jll.jl/releases/download/v986.0.1/CCTools-extract_log-v986.0.1-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
